# Generated by Django 2.2.9 on 2020-05-04 13:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of this entry', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A verbose description of this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this entry was created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this entry was last updated at')),
                ('removed', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(help_text='The unique code of this company', max_length=16, unique=True)),
                ('market_capacity', models.DecimalField(decimal_places=3, help_text='Market capacity', max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of this entry', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A verbose description of this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this entry was created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this entry was last updated at')),
                ('removed', models.BooleanField(db_index=True, default=False)),
                ('price_date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=19)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_price_history', to='stock.Company')),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceDailyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of this entry', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A verbose description of this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this entry was created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this entry was last updated at')),
                ('removed', models.BooleanField(db_index=True, default=False)),
                ('price_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=19)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_price_daily_history', to='stock.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Name')),
                ('full_name', models.TextField(blank=True, help_text='Name of sector ', verbose_name='Fullname')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modified')),
                ('removed', models.BooleanField(db_index=True, default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('sector_level', models.PositiveIntegerField(editable=False)),
                ('parent_sector', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sectors', to='stock.Sector')),
            ],
            options={
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='stock.Sector'),
        ),
    ]
