# Generated by Django 2.2.9 on 2020-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='number_of_companies',
            field=models.IntegerField(default=0, verbose_name='Number of companies'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='internal id'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_index',
            field=models.CharField(max_length=128, null=True, verbose_name='Sector Index'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_type',
            field=models.CharField(max_length=128, null=True, verbose_name='Type'),
        ),
    ]
