# Generated by Django 2.2.9 on 2020-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200505_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricehistory',
            name='ask_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='bid_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='price_change',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='price_change_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='trade_count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='trade_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricedailyhistory',
            name='close_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricedailyhistory',
            name='high_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricedailyhistory',
            name='low_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricedailyhistory',
            name='open_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricedailyhistory',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='close_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='high_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='low_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='open_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
