# Generated by Django 2.2.9 on 2020-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200506_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsxIndexDailyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of this entry', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A verbose description of this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this entry was created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this entry was last updated at')),
                ('removed', models.BooleanField(db_index=True, default=False)),
                ('index_name', models.CharField(max_length=128, verbose_name='Index Name')),
                ('index_date', models.DateField()),
                ('open_index', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('close_index', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('high_index', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('low_index', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AsxIndexHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of this entry', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A verbose description of this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time this entry was created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this entry was last updated at')),
                ('removed', models.BooleanField(db_index=True, default=False)),
                ('index_name', models.CharField(max_length=128, verbose_name='Index Name')),
                ('index_date', models.DateTimeField()),
                ('close_index', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
