# Generated by Django 2.2.9 on 2020-05-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200506_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=128, verbose_name='Data Name')),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InitialDataUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=128, verbose_name='Data Name')),
                ('code', models.CharField(max_length=128, verbose_name='Code Name')),
                ('updated_date', models.DateField()),
            ],
        ),
    ]
