from datetime import date

date_fmt = '%Y-%m-%d'

HOLD_STOCK = 0
BUY_STOCK = 1
SELL_STOCK = 2
TOP_UP_FUND = 3
WITHDRAW_FUND = 4
MIN_STOCK_DATE = date(2010, 10, 10)
DB_FILE_NAME = 'db.sqlite3'
MINIMUM_SIMULATION_DAYS = 100
RANDOM_START_DAYS_PERIOD = 100
DEFAULT_INITIAL_FUND = 100000
TRANSACTION_START_HOUR = 10
TRANSACTION_END_HOUR = 16
RENDER_DEFAULT_DISPLAY_DAYS = 20
DEFAULT_EXPECTED_FUND_INCREASE_RATIO = 2.0
DEFAULT_EXPECTED_FUND_DECREASE_RATIO = 0.2

